FROM nginx:1-alpine

RUN apk add nodejs

COPY ./build /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/conf.d/default.conf
COPY docker/generate-config.js /

EXPOSE 80

CMD node generate-config.js && nginx -g "daemon off;"
