export const REGISTER = "REGISTER";
export const SIGN_IN = "SIGN_IN";
export const SIGN_OUT = "SIGN_OUT";
export const SET_SERVER_URL = "SET_SERVER_URL";
export const SET_SELF_HOSTED = "SET_SELF_HOSTED";

export const SET_MENU_STYLE = "SET_MENU_STYLE";

export const SET_VOCAB_ACTIVE = "SET_VOCAB_ACTIVE";
export const SET_VOCAB_ACTIVATE = "SET_VOCAB_ACTIVATE";
export const SET_GROUP_ACTIVATE = "SET_GROUP_ACTIVATE";

export const SET_TABLE_PAGE_SIZE = "SET_TABLE_PAGE_SIZE";

export const SET_LEARNED_PACKAGE = "SET_LEARNED_PACKAGE";
